---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
          # resources:
          #   limits:
          #     cpu: "0.20"
          #     memory: "64Mi"
          #   requests:
          #     cpu: "0.10"        
          #     memory: "32Mi"
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      # nodePort: 31033

---
# This secret can also be created from the command line using environment variables
#
# export DATABASE_URI='postgresql://<place-url-to-database-here>'
# export POSTGRES_PASSWORD='<place-password-here>'
#
# kubectl create secret generic postgres-creds \
#     --from-literal=password=$POSTGRES_PASSWORD
#     --from-literal=database_uri=$DATABASE_URI
#
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: cG9zdGdyZXM=
  database_uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
