---
# Python 3 with PostgreSQL
version: "3"

services:
  app:
    container_name: shopcarts.app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile    
    hostname: nyu
    volumes:
      - ..:/app
      - ~/.bluemix/apikey_shopcarts.json:/home/vscode/.ibm/apikey_shopcarts.json
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_DEBUG: "True"
      PORT: 8000
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    container_name: shopcarts.db
    image: postgres:alpine
    # Uncomment ports to access database from your computer (optional)
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres:

networks:
  dev:
